---
abstract: 'Watch for changes to files, cross-platform style'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Data::Dumper: 0
  Exporter: 0
  File::Path: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
  base: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-ChangeNotify
requires:
  Carp: 0
  Class::Load: 0
  File::Find: 0
  File::Spec: 0
  List::MoreUtils: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  Time::HiRes: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-ChangeNotify
  repository: git://git.urth.org/File-ChangeNotify.git
version: 0.21
