---
abstract: 'Watch for changes to files, cross-platform style'
author:
  - 'Dave Rolsky, E<lt>autarch@urth.orgE<gt>'
build_requires:
  File::Path: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-ChangeNotify
provides:
  File::ChangeNotify:
    file: lib/File/ChangeNotify.pm
    version: 0.13
  File::ChangeNotify::Event:
    file: lib/File/ChangeNotify/Event.pm
    version: 0.13
  File::ChangeNotify::Watcher:
    file: lib/File/ChangeNotify/Watcher.pm
    version: 0.13
  File::ChangeNotify::Watcher::Default:
    file: lib/File/ChangeNotify/Watcher/Default.pm
    version: 0.13
  File::ChangeNotify::Watcher::Inotify:
    file: lib/File/ChangeNotify/Watcher/Inotify.pm
    version: 0.13
  File::ChangeNotify::Watcher::KQueue:
    file: lib/File/ChangeNotify/Watcher/KQueue.pm
    version: 0.13
requires:
  Carp: 0
  Class::MOP: 0
  File::Find: 0
  File::Spec: 0
  Module::Pluggable::Object: 0
  Moose: 0
  MooseX::Params::Validate: 0.08
  MooseX::SemiAffordanceAccessor: 0
  Time::HiRes: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-ChangeNotify
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/File-ChangeNotify
version: 0.13
