---
abstract: 'Watch for changes to files, cross-platform style'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Path: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-ChangeNotify
requires:
  Carp: 0
  Class::MOP: 0
  File::Find: 0
  File::Spec: 0
  Module::Pluggable::Object: 0
  Moose: 0
  MooseX::Params::Validate: 0.08
  MooseX::SemiAffordanceAccessor: 0
  Time::HiRes: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-ChangeNotify
  repository: http://hg.urth.org/hg/File-ChangeNotify
version: 0.17
